#!/bin/bash

# rajouter "source ~/scripts/boot_config" dans "/home/dionisos/.profile et .bashrc" !!!

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi


alias rm='echo "rm desactivated, use trash"'
alias purge='echo "trash-empty 3 (vieux de plus de 3 jours)" && trash-empty 3'
alias cp='cp -i'
alias mv='mv -i'
alias ema='cd ~/.emacs.d/'
alias cd..='cd ..'
alias gocpp="cd ~/projets/programmation/c++/"
alias gopy="cd ~/projets/programmation/python/"
alias r="ranger"
alias ll='ls -alF'
alias t="trizen"

export HISTFILESIZE=200000
export HISTSIZE=100000
export HISTCONTROL=ignoredups:ignorespace
# /!\ del this var in .bash_rc /!\
export SVN_EDITOR="emacsclient -c"
export EDITOR="emacsclient -c"
PATH=$PATH:"./"
PATH=$PATH:"~/scripts"
PATH=$PATH:"~/.local/bin"
PATH=$PATH:"/opt/java/bin"
export PATH
export LANG="fr_FR.utf8"
export PAGER=less
export XLIB_SKIP_ARGB_VISUALS=1 # for skype
export BORG_REPO=ssh://dionisos@dionisos_pc:22/home/dionisos/save_portable

# c-v + key for find the character sequence emitted by key
bind '"\e[Z":menu-complete'
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'
# c-r for search in history
source /etc/profile.d/autojump.bash
export PROMPT_COMMAND="history -a && $PROMPT_COMMAND"
# expand command before verifying this
shopt -s histverify
# disable XON/XOFF then you can use ctrl-s with ctrl-r
stty -ixon

