#!/bin/sh

php app/console doctrine:database:drop --force --connection=test
php app/console doctrine:database:create --connection=test
php app/console doctrine:schema:update --force --em=test
php app/console doctrine:fixtures:load --em=test
