#!/bin/bash

if [[ $# -ne 1 ]]
then
	echo "give only one file/directory to delete"
	echo "$# given"
	echo "$@"
	exit 1
fi

if [[ -a "$1" ]] || [[ -h "$1" ]]
then
	from_file="$1"
	file_basename=$(basename "$from_file")
	to_file="$HOME/.local/share/Trash/files/$file_basename"
	while [[ -e "$to_file" ]]
	do
		to_file="$to_file"_
	done
	mv "$from_file" "$to_file"
else
	echo "\"$1\" not found"
fi



