#!/bin/sh
shopt -s expand_aliases
# source ~/.bash_aliases

if [ $# -ne 2 ]
then
    echo "This command should be used like it:"
    echo 'for_each_file "$(ls)" echo'
	exit 1
fi

while read -r line
do
    echo "$2 $line"
    eval $2 "$line"
done <<< "$1"
