#!/usr/bin/env bash

echo "get config files in '~/script'"
rsync -au --progress ~/.config/lf/lfrc ~/scripts/config/lf/
rsync -au --progress ~/.config/qtile/config.py ~/scripts/config/qtile/
rsync -au --progress ~/.config/qtile/autostart.sh ~/scripts/config/qtile/
