#!/bin/sh

cp ~/.config/ranger/commands.py ~/scripts/config/ranger/
cp ~/.config/ranger/rc.conf ~/scripts/config/ranger/
cp ~/.config/ranger/rifle.conf ~/scripts/config/ranger/
cp ~/.config/qtile/config.py ~/scripts/config/qtile/
cp ~/.config/qtile/autostart.sh ~/scripts/config/qtile/
