#!/usr/bin/env bash

echo "Start the git save process"

git_dir=(
		"/home/dionisos/organisation/"
		"/home/dionisos/.config/emacs"
		"/home/dionisos/.config/emacs/private"
		"/home/dionisos/scripts"
		"/home/dionisos/projets/RD/tiddly_perso/"
		"/home/dionisos/personnelle/private_config/"
)

total=${#git_dir[@]}
index=1

for dir in "${git_dir[@]}"
do
		if [[ -f "/home/dionisos/abort_git_save" ]]
		then
			 echo "Abort git_save"
			 rm "/home/dionisos/abort_git_save"
			 exit 1
		fi

		name=$(basename "$dir")
		cd "$dir"
		echo "$name"
		xonsh -DPROMPT="{env_name}{BOLD_GREEN}{user}@{hostname} $name $index/$total{BOLD_BLUE} {cwd}{branch_color}{curr_branch: {}}{RESET} {BOLD_BLUE}{prompt_end}{RESET} "
		(( "index+=1" ))
done

echo "Finished :-)"
