#!/usr/bin/env bash


commands=$(more ~/.bash_history | egrep -v "(^#|^$)" | awk '{print $1}'|sort|uniq -c|sort -rg)

sum=$(echo -e "$commands" | awk '{SUM += $1}END{print SUM}')

echo "sum = " $sum
echo "list of commands:"
echo "$commands"
