#!/bin/sh

case "$1" in
		start)
				if [ -f "/home/dionisos/11-media-by-label-with-pmount.rules" ]; then
						doas mv /home/dionisos/11-media-by-label-with-pmount.rules /etc/udev/rules.d/
						echo "automatique-mount start"
				else
						echo "already start"
				fi
				
				;;
		stop)
				if [ -f "/etc/udev/rules.d/11-media-by-label-with-pmount.rules" ]; then
						doas mv /etc/udev/rules.d/11-media-by-label-with-pmount.rules /home/dionisos/
						echo "automatique-mount stop"
				else
						echo "already stop"
				fi

				;;
		*)
				echo "usage: $0 {start|stop}"
esac
