#!/bin/bash

if [ "$1" != "" ] && [ "$1" != "-c" ]
then
	echo "pager [-c]"
	exit 1
fi

date=`date "+%Y-%m-%d-%S-%N"`
file="/tmp/pager_$date"

> $file

while read line
do
	 echo $line >> $file
done

if [ "$1" == "-c" ]
then
	emacsclient -c -nw $file
elif [ "$1" == "" ]
then
	emacsclient -c $file
else
	echo "bug"
fi

rm $file
