#!/bin/bash

date=$(format_date)

import -windows "$1" "/home/dionisos/screenshot/$1_screenshot_$date.png"
convert "/home/dionisos/screenshot/$1_screenshot_$date.png" "/home/dionisos/screenshot/$1_screenshot_$date.jpg"
rm "/home/dionisos/screenshot/$1_screenshot_$date.png"
