#!/bin/bash

date=$(format_date)

import -window root /home/dionisos/screenshot/root_screen_$date.png
convert /home/dionisos/screenshot/root_screen_$date.png /home/dionisos/screenshot/root_screen_$date.jpg
rm /home/dionisos/screenshot/root_screen_$date.png
