#!/bin/bash

date=$(format_date)

windows=$(wmctrl -l | grep "$1" | head -1 | awk '{print $1}')

if [ "$windows" == "" ]
then
	echo "windows not found"
	exit 1
fi

wmctrl -a "$1"
sleep 1
import -window "$windows" "/home/dionisos/screenshots/screenshot_$date.png"
convert "/home/dionisos/screenshots/screenshot_$date.png" "/home/dionisos/screenshots/screenshot_$date.jpg"
trash "/home/dionisos/screenshots/screenshot_$date.png"
