#!/bin/bash

date=$(format_date)

import -window root /home/dionisos/screenshots/root_screen_$date.png
convert /home/dionisos/screenshots/root_screen_$date.png /home/dionisos/screenshots/root_screen_$date.jpg
trash /home/dionisos/screenshots/root_screen_$date.png
