#!/usr/bin/env bash

echo "clear css and js"
/home/dionisos/scripts/symf_clear_cssjs
echo "change owner"
/home/dionisos/scripts/symf_owner
echo "change permission"
/home/dionisos/scripts/symf_droit
echo "clear cache"
/home/dionisos/scripts/symf_clear_cache
echo "change owner"
/home/dionisos/scripts/symf_owner
echo "change permission"
/home/dionisos/scripts/symf_droit
