#!/bin/bash

/home/dionisos/script/symf_clear_cssjs
/home/dionisos/script/symf_owner
/home/dionisos/script/symf_droit
/home/dionisos/script/symf_clear_cache
/home/dionisos/script/symf_owner
/home/dionisos/script/symf_droit
