#!/bin/bash

sudo -u http php ./app/console cache:clear
sudo -u http php ./app/console cache:clear --env=prod
sudo -u http php vendor/sensio/distribution-bundle/Sensio/Bundle/DistributionBundle/Resources/bin/build_bootstrap.php
