#!/usr/bin/env bash

doas -u http php ./app/console cache:clear
doas -u http php ./app/console cache:clear --env=prod
doas -u http php vendor/sensio/distribution-bundle/Sensio/Bundle/DistributionBundle/Resources/bin/build_bootstrap.php
doas -u http php composer.phar dumpautoload --optimize -v
