#!/usr/bin/env bash


if [ $# -ne 1 ] || { [ "$1" != "push" ] && [ "$1" != "pull" ]; }
then
		echo "The first (and only) parameter should be 'push' or 'pull'"
		exit 1
else
		command="$1"
fi

if [ -d "/mnt/dd/transferts" ]
then
		cd "/mnt/dd/transferts" || exit
else
		echo "'/mnt/dd/transferts' not found, are the external disk mounted ?"
		exit 1
fi

date="$(date "+%d-%m-%Y_%Hh%M")"

divers_dir="./divers"
divers_local_dir="/home/dionisos/téléchargements/transfer_$(date +%d-%m-%Y)/"
git_dir="./git_save"

log_path="./log.txt"
from_path="./from.txt"
date_path="./date.txt"

function log() {
		printf "%b\n" "$1" >> "$log_path"
		printf "Log : %b\n" "$1"
}

if [[ ! -d "$divers_dir" ]]
then
		mkdir -p "$divers_dir"
fi

if [[ ! -d "$git_dir" ]]
then
		mkdir -p "$git_dir"
fi

if [[ ! -d "$log_path" ]]
then
		touch "$log_path"
fi

if [[ ! -d "$from_path" ]]
then
		echo "nobody" > "$from_path"
fi

if [[ ! -d "$date_path" ]]
then
		echo "no date" > "$date_path"
fi

last_from="$(more $from_path)"
last_date="$(more $date_path)"


divers_path_to_save=("/home/dionisos/.ssh"
										 "/home/dionisos/logiciels/shaarli/data"
										 "/home/dionisos/.aspell.fr.pws"
										 "/home/dionisos/.aspell.en.pws"
										 "/home/dionisos/personnelle/administratif"
										 "/home/dionisos/projets/programmation/julia"
										 "/home/dionisos/projets/programmation/python"
										 "/home/dionisos/projets/programmation/unity"
										 "/home/dionisos/projets/programmation/name_conventions"
										 #https://support.mozilla.org/en-US/kb/profiles-where-firefox-stores-user-data
										 "/home/dionisos/.mozilla/firefox/cysf0lb1.dev-edition-default-1680100960076/places.sqlite"
										 "/home/dionisos/.mozilla/firefox/cysf0lb1.dev-edition-default-1680100960076/favicons.sqlite"
										)

log "$date"

if [ "$command" == "pull" ]
then
		log "Pull transfer : from '$last_from' (at $last_date) to '$(uname -n)'"
else
		log "Push transfer : from '$(uname -n)'"
fi

if git_save
then
		log "git_save done"
else
		log "End : git_save aborted (code:$?)\n"
		exit 1
fi

if [ "$command" == "pull" ]
then
		if [ "$last_from" == "$(uname -m)" ]
		then
				echo "Last pull transfer from same computer ($last_from), did you forget to do it on the other one ?"
				log "Pull failed : Push then Pull from same computer"
				exit 1
		fi
		rsync -au --progress "$divers_dir" "$divers_local_dir"
		log "Transfer of divers completed"
elif [ "$command" == "push" ]
then

		for path in "${divers_path_to_save[@]}"
		do
				rsync -au --progress "$path" "$divers_dir"
		done
		rm "$git_dir"
		rsync -au --progress "/home/dionisos/personnelle/records_and_save/git_save/" "$git_dir"
		echo "Transfer of divers completed"
fi

echo "$date" > "$date_path"
uname -n > "$from_path"
log "End : everything seems ok\n"
